# Hello, HENNGE! Dockerfile for Production

FROM node:24.20-alpine

WORKDIR /app

ENV NODE_ENV=production

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --only=prod

COPY . .

RUN npm run build
